# Generated by Django 3.1.5 on 2021-02-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='employ_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
