# Generated by Django 3.1.1 on 2021-05-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_status_employ_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='joining_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='totalleave',
            name='sick_leave_alloted',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
