# Generated by Django 3.1.1 on 2021-05-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_auto_20210514_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='overday',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
